/**************************************************************************/
// dyntable.cpp - for lookups, was once dynamically generated
/***************************************************************************
 * The Dawn of Time v1.69r (c)1997-2004 Michael Garratt                    *
 * >> A number of people have contributed to the Dawn codebase, with the   *
 *    majority of code written by Michael Garratt - www.dawnoftime.org     *
 * >> To use this source code, you must fully comply with the dawn license *
 *    in licenses.txt... In particular, you may not remove this copyright  *
 *    notice.                                                              *
 **************************************************************************/
#include "include.h"
#include "dynamics.h"
#include "magic.h"

dynlookup_type dynlookup_table[]={
	{ "abjuration",             DYNTYPE_REALM, &gsn_abjuration },
	{ "alteration",             DYNTYPE_REALM, &gsn_alteration },
	{ "conjuration",            DYNTYPE_REALM, &gsn_conjuration },
	{ "illusion",               DYNTYPE_REALM, &gsn_illusion },
	{ "phantasm",               DYNTYPE_REALM, &gsn_phantasm },
	{ "evocation",              DYNTYPE_REALM, &gsn_evocation },
	{ "enchantment",            DYNTYPE_REALM, &gsn_enchantment },
	{ "charm",                  DYNTYPE_REALM, &gsn_charm },
	{ "divination",             DYNTYPE_REALM, &gsn_divination },
	{ "necromancy",             DYNTYPE_REALM, &gsn_necromancy },
	{ "earth",                  DYNTYPE_REALM, &gsn_earth },
	{ "air",                    DYNTYPE_REALM, &gsn_air },
	{ "fire",                   DYNTYPE_REALM, &gsn_fire },
	{ "water",                  DYNTYPE_REALM, &gsn_water },
	{ "weather",                DYNTYPE_REALM, &gsn_weather },
	{ "protection",             DYNTYPE_REALM, &gsn_protection },
	{ "plant",                  DYNTYPE_REALM, &gsn_plant },
	{ "law",                    DYNTYPE_REALM, &gsn_law },
	{ "sun",                    DYNTYPE_REALM, &gsn_sun },
	{ "animal",                 DYNTYPE_REALM, &gsn_animal },
	{ "combat",                 DYNTYPE_REALM, &gsn_combat },
	{ "creation",               DYNTYPE_REALM, &gsn_creation },
	{ "time",                   DYNTYPE_REALM, &gsn_time },
	{ "summoning",              DYNTYPE_REALM, &gsn_summoning },
	{ "healing",                DYNTYPE_REALM, &gsn_healing },
	{ "beguiling",				DYNTYPE_REALM, &gsn_beguiling },
	{ "ceremonial",				DYNTYPE_REALM, &gsn_ceremonial },
	{ "epic",					DYNTYPE_REALM, &gsn_epic },
	{ "esoteric",				DYNTYPE_REALM, &gsn_esoteric },
	{ "ethereal",				DYNTYPE_REALM, &gsn_ethereal },
	{ "holistic",				DYNTYPE_REALM, &gsn_holistic },
	{ "requiem",				DYNTYPE_REALM, &gsn_requiem },
	{ "acid blast",             DYNTYPE_SPELL, &gsn_acid_blast },
	{ "alarm",					DYNTYPE_SPELL, &gsn_alarm },
	{ "eagle essence",			DYNTYPE_SPELL, &gsn_animal_essence },
	{ "armour",                 DYNTYPE_SPELL, &gsn_armor },
	{ "augment hearing",        DYNTYPE_SPELL, &gsn_augment_hearing },
	{ "aura of temperance",     DYNTYPE_SPELL, &gsn_aura_of_temperance },
	{ "barkskin",               DYNTYPE_SPELL, &gsn_barkskin },
	{ "benedict",               DYNTYPE_SPELL, &gsn_benedict },
	{ "bless",                  DYNTYPE_SPELL, &gsn_bless },
	{ "blessed garments",       DYNTYPE_SPELL, &gsn_blessed_garments },
	{ "blindness",              DYNTYPE_SPELL, &gsn_blindness },
	{ "blink",					DYNTYPE_SPELL, &gsn_blink },
	{ "burning hands",          DYNTYPE_SPELL, &gsn_burning_hands },
	{ "call lightning",         DYNTYPE_SPELL, &gsn_call_lightning },
	{ "calm",                   DYNTYPE_SPELL, &gsn_calm },
	{ "cancellation",           DYNTYPE_SPELL, &gsn_cancellation },
	{ "canticle of warding",	DYNTYPE_SPELL, &gsn_canticle_of_warding },
	{ "cantrip",                DYNTYPE_SPELL, &gsn_cantrip },
	{ "cause fear",             DYNTYPE_SPELL, &gsn_cause_fear },
	{ "cause headache",         DYNTYPE_SPELL, &gsn_cause_headache },
	{ "cause critical",         DYNTYPE_SPELL, &gsn_cause_critical },
	{ "cause light",            DYNTYPE_SPELL, &gsn_cause_light },
	{ "cause serious",          DYNTYPE_SPELL, &gsn_cause_serious },
	{ "chain lightning",        DYNTYPE_SPELL, &gsn_chain_lightning },
	{ "change sex",             DYNTYPE_SPELL, &gsn_change_sex },
	{ "charm person",           DYNTYPE_SPELL, &gsn_charm_person },
	{ "chaos lace",             DYNTYPE_SPELL, &gsn_chaos_lace },
	{ "chaotic poison",         DYNTYPE_SPELL, &gsn_chaotic_poison },
  	{ "chemistry",				DYNTYPE_SKILL, &gsn_chemistry},
	{ "chill shield",           DYNTYPE_SPELL, &gsn_chill_shield },
	{ "chill touch",            DYNTYPE_SPELL, &gsn_chill_touch },
	{ "clarity",				DYNTYPE_SPELL, &gsn_clarity },
	{ "colour spray",           DYNTYPE_SPELL, &gsn_colour_spray },
	{ "commune with dead",		DYNTYPE_SPELL, &gsn_commune_with_dead },
	{ "cone cold",              DYNTYPE_SPELL, &gsn_cone_cold },
	{ "continual light",        DYNTYPE_SPELL, &gsn_continual_light },
	{ "control weather",        DYNTYPE_SPELL, &gsn_control_weather },
	{ "create buffet",          DYNTYPE_SPELL, &gsn_create_buffet },
	{ "create food",            DYNTYPE_SPELL, &gsn_create_food },
	{ "create rose",            DYNTYPE_SPELL, &gsn_create_rose },
	{ "create spring",          DYNTYPE_SPELL, &gsn_create_spring },
	{ "create water",           DYNTYPE_SPELL, &gsn_create_water },
	{ "cure blindness",         DYNTYPE_SPELL, &gsn_cure_blindness },
	{ "cure chaotic poison",    DYNTYPE_SPELL, &gsn_cure_chaotic_poison },
	{ "cure critical",          DYNTYPE_SPELL, &gsn_cure_critical },
	{ "cure deafness",          DYNTYPE_SPELL, &gsn_cure_deafness },
	{ "cure disease",           DYNTYPE_SPELL, &gsn_cure_disease },
	{ "cure headache",          DYNTYPE_SPELL, &gsn_cure_headache },
	{ "cure light",             DYNTYPE_SPELL, &gsn_cure_light },
	{ "cure poison",            DYNTYPE_SPELL, &gsn_cure_poison },
	{ "cure serious",           DYNTYPE_SPELL, &gsn_cure_serious },
	{ "curse",                  DYNTYPE_SPELL, &gsn_curse },
	{ "cutting wind",           DYNTYPE_SPELL, &gsn_cutting_wind },
	{ "cyclone",                DYNTYPE_SPELL, &gsn_cyclone },
	{ "deafness",               DYNTYPE_SPELL, &gsn_deafness },
	{ "decay",                  DYNTYPE_SPELL, &gsn_decay },
	{ "detect evil",            DYNTYPE_SPELL, &gsn_detect_evil },
	{ "detect good",            DYNTYPE_SPELL, &gsn_detect_good },
	{ "dehydration",            DYNTYPE_SPELL, &gsn_dehydration },
	{ "detect hidden",          DYNTYPE_SPELL, &gsn_detect_hidden },
	{ "detect invis",           DYNTYPE_SPELL, &gsn_detect_invis },
	{ "detect magic",           DYNTYPE_SPELL, &gsn_detect_magic },
	{ "detect poison",          DYNTYPE_SPELL, &gsn_detect_poison },
	{ "detect scry",            DYNTYPE_SPELL, &gsn_detect_scry },
	{ "detect treeform",		DYNTYPE_SPELL, &gsn_detect_treeform },
	{ "disorientation",         DYNTYPE_SPELL, &gsn_disorientation },
	{ "dispel evil",            DYNTYPE_SPELL, &gsn_dispel_evil },
	{ "dispel good",            DYNTYPE_SPELL, &gsn_dispel_good },
	{ "dispel magic",           DYNTYPE_SPELL, &gsn_dispel_magic },
	{ "divine light",           DYNTYPE_SPELL, &gsn_divine_light },
	{ "downdraft",              DYNTYPE_SPELL, &gsn_downdraft },
	{ "dragon strength",        DYNTYPE_SPELL, &gsn_dragon_strength },
	{ "druidstaff",				DYNTYPE_SPELL, &gsn_druidstaff },
	{ "drunkenness",            DYNTYPE_SPELL, &gsn_drunkeness },
	{ "drain weapon",           DYNTYPE_SPELL, &gsn_drain_blade },
	{ "earthquake",             DYNTYPE_SPELL, &gsn_earthquake },
	{ "earthwalk",              DYNTYPE_SPELL, &gsn_earthwalk },
	{ "empower weapon",         DYNTYPE_SPELL, &gsn_empower_blade },
	{ "enchant armour",         DYNTYPE_SPELL, &gsn_enchant_armor },
	{ "enchant weapon",         DYNTYPE_SPELL, &gsn_enchant_weapon },
	{ "energy drain",           DYNTYPE_SPELL, &gsn_energy_drain },
	{ "extension",              DYNTYPE_SPELL, &gsn_extension },
	{ "faerie fire",            DYNTYPE_SPELL, &gsn_faerie_fire },
	{ "faerie fog",             DYNTYPE_SPELL, &gsn_faerie_fog },
	{ "farsight",               DYNTYPE_SPELL, &gsn_farsight },
	{ "fear magic",             DYNTYPE_SPELL, &gsn_fear_magic },
	{ "fiery armour",           DYNTYPE_SPELL, &gsn_fiery_armour },
	{ "fireball",               DYNTYPE_SPELL, &gsn_fireball },
	{ "fireproof",              DYNTYPE_SPELL, &gsn_fireproof },
	{ "fire shield",            DYNTYPE_SPELL, &gsn_fire_shield },
	{ "frostball",              DYNTYPE_SPELL, &gsn_frostball },
	{ "flame weapon",           DYNTYPE_SPELL, &gsn_flame_blade },
	{ "flamestrike",            DYNTYPE_SPELL, &gsn_flamestrike },
	{ "fling",                  DYNTYPE_SPELL, &gsn_fling },
	{ "fly",                    DYNTYPE_SPELL, &gsn_fly },
	{ "floating disc",          DYNTYPE_SPELL, &gsn_floating_disc },
	{ "frenzy",                 DYNTYPE_SPELL, &gsn_frenzy },
	{ "frost weapon",           DYNTYPE_SPELL, &gsn_frost_blade },
	{ "gate",                   DYNTYPE_SPELL, &gsn_gate },
	{ "giant strength",         DYNTYPE_SPELL, &gsn_giant_strength },
	{ "harm",                   DYNTYPE_SPELL, &gsn_harm },
	{ "haste",                  DYNTYPE_SPELL, &gsn_haste },
	{ "heal",                   DYNTYPE_SPELL, &gsn_heal },
	{ "heat metal",             DYNTYPE_SPELL, &gsn_heat_metal },
	{ "herbalism",				DYNTYPE_SKILL, &gsn_herbalism},
	{ "high area attack",       DYNTYPE_SPELL, &gsn_high_area_attack },
	{ "higher learning",		DYNTYPE_SPELL, &gsn_higher_learning },
	{ "holy aura",              DYNTYPE_SPELL, &gsn_holy_aura },
	{ "holy beam",              DYNTYPE_SPELL, &gsn_holy_beam },
	{ "holy word",              DYNTYPE_SPELL, &gsn_holy_word },
	{ "ice storm",              DYNTYPE_SPELL, &gsn_ice_storm },
	{ "icy armour",             DYNTYPE_SPELL, &gsn_icy_armour },
	{ "identify",               DYNTYPE_SPELL, &gsn_identify },
	{ "illusions grandeur",     DYNTYPE_SPELL, &gsn_illusions_grandeur },
	{ "immolation",				DYNTYPE_SPELL, &gsn_immolation },
	{ "improved phantasm",      DYNTYPE_SPELL, &gsn_improved_phantasm },
	{ "induce sleep",           DYNTYPE_SPELL, &gsn_induce_sleep },
	{ "infravision",            DYNTYPE_SPELL, &gsn_infravision },
	{ "invisibility",           DYNTYPE_SPELL, &gsn_invisibility },
	{ "iron skin",              DYNTYPE_SPELL, &gsn_iron_skin },
	{ "know alignment",         DYNTYPE_SPELL, &gsn_know_alignment },
	{ "low area attack",        DYNTYPE_SPELL, &gsn_low_area_attack },
	{ "lightning bolt",         DYNTYPE_SPELL, &gsn_lightning_bolt },
	{ "locate object",          DYNTYPE_SPELL, &gsn_locate_object },
	{ "logic",					DYNTYPE_SPELL, &gsn_logic },
	{ "lucidity",				DYNTYPE_SPELL, &gsn_lucidity },
	{ "magic resistance",       DYNTYPE_SPELL, &gsn_magic_resistance },
	{ "magic missile",          DYNTYPE_SPELL, &gsn_magic_missile },
	{ "magical vestment",       DYNTYPE_SPELL, &gsn_magical_vestment },
	{ "maledict",               DYNTYPE_SPELL, &gsn_maledict },
	{ "mass healing",           DYNTYPE_SPELL, &gsn_mass_healing },
	{ "mass invis",             DYNTYPE_SPELL, &gsn_mass_invis },
	{ "mid area attack",        DYNTYPE_SPELL, &gsn_mid_area_attack },
	{ "mirage",                 DYNTYPE_SPELL, &gsn_mirage },
	{ "mithril glaze",          DYNTYPE_SPELL, &gsn_mithril_glaze },
	{ "mindspeak",				DYNTYPE_SPELL, &gsn_mindspeak },
	{ "mnemonics",				DYNTYPE_SPELL, &gsn_mnemonics },
	{ "mute",					DYNTYPE_SPELL, &gsn_mute },
	{ "naturespeak",            DYNTYPE_SPELL, &gsn_naturespeak },
	{ "nexus",                  DYNTYPE_SPELL, &gsn_nexus },
	{ "night eyes",				DYNTYPE_SPELL, &gsn_night_eyes },
	{ "night of the leonids",	DYNTYPE_SPELL, &gsn_night_of_the_leonids },
	{ "oak shield",             DYNTYPE_SPELL, &gsn_oak_shield },
	{ "ogre strength",          DYNTYPE_SPELL, &gsn_ogre_strength },
	{ "otterlungs",             DYNTYPE_SPELL, &gsn_otterlungs },
	{ "pass door",              DYNTYPE_SPELL, &gsn_pass_door },
	{ "pass without trace",		DYNTYPE_SPELL, &gsn_pass_without_trace },
	{ "persuasion",				DYNTYPE_SPELL, &gsn_persuasion },
	{ "phantasmal force",       DYNTYPE_SPELL, &gsn_phantasmal_force },
	{ "permanance",             DYNTYPE_SPELL, &gsn_permanance },
	{ "pine needles",			DYNTYPE_SPELL, &gsn_pine_needles },
	{ "plague",                 DYNTYPE_SPELL, &gsn_plague },
	{ "poison",                 DYNTYPE_SPELL, &gsn_poison },
	{ "poison immunity",        DYNTYPE_SPELL, &gsn_poison_immunity },
	{ "poison rain",            DYNTYPE_SPELL, &gsn_poison_rain },
	{ "possession",             DYNTYPE_SPELL, &gsn_possession},
	{ "portal",                 DYNTYPE_SPELL, &gsn_portal },
	{ "assistance",             DYNTYPE_SPELL, &gsn_prayer },
	{ "prismatic spray",        DYNTYPE_SPELL, &gsn_prismatic_spray },
	{ "protection acid",        DYNTYPE_SPELL, &gsn_protection_acid },
	{ "protection cold",        DYNTYPE_SPELL, &gsn_protection_cold },
	{ "protection evil",        DYNTYPE_SPELL, &gsn_protection_evil },
	{ "protection fire",        DYNTYPE_SPELL, &gsn_protection_fire },
	{ "protection good",        DYNTYPE_SPELL, &gsn_protection_good },
	{ "protection lightning",   DYNTYPE_SPELL, &gsn_protection_lightning },
	{ "rage",                   DYNTYPE_SPELL, &gsn_rage },
	{ "recharge",               DYNTYPE_SPELL, &gsn_recharge },
	{ "refresh",                DYNTYPE_SPELL, &gsn_refresh },
	{ "regeneration",           DYNTYPE_SPELL, &gsn_regeneration },
	{ "rejuvenate",             DYNTYPE_SPELL, &gsn_rejuvinate },
	{ "remove curse",           DYNTYPE_SPELL, &gsn_remove_curse },
	{ "resist poison",          DYNTYPE_SPELL, &gsn_resist_poison },
	{ "resist weapons",         DYNTYPE_SPELL, &gsn_resist_weapons },
	{ "rocky skin",             DYNTYPE_SPELL, &gsn_rocky_skin },
	{ "rune edge",              DYNTYPE_SPELL, &gsn_rune_edge },
	{ "runic blade",            DYNTYPE_SPELL, &gsn_runic_blade },
	{ "sanctuary",              DYNTYPE_SPELL, &gsn_sanctuary },
	{ "shadowflight",			DYNTYPE_SPELL, &gsn_shadowflight },
	{ "shaping the chaos",      DYNTYPE_SPELL, &gsn_shaping_the_chaos },
	{ "shelter",                DYNTYPE_SPELL, &gsn_shelter },
	{ "shield",                 DYNTYPE_SPELL, &gsn_shield },
	{ "shocking grasp",         DYNTYPE_SPELL, &gsn_shocking_grasp },
	{ "shrink",					DYNTYPE_SPELL, &gsn_shrink },
	{ "sleep",                  DYNTYPE_SPELL, &gsn_sleep },
	{ "slow",                   DYNTYPE_SPELL, &gsn_slow },
	{ "smite",                  DYNTYPE_SPELL, &gsn_smite },
	{ "spirit hammer",			DYNTYPE_SPELL, &gsn_spirit_hammer },
	{ "spirit walk",            DYNTYPE_SPELL, &gsn_spirit_walk },
	{ "stone skin",             DYNTYPE_SPELL, &gsn_stone_skin },
	{ "starvation",             DYNTYPE_SPELL, &gsn_starvation },
	{ "sober",                  DYNTYPE_SPELL, &gsn_sober },
    { "strength of the land",   DYNTYPE_SPELL, &gsn_strength_of_the_land },
	{ "summon",                 DYNTYPE_SPELL, &gsn_summon },
	{ "sunfire",                DYNTYPE_SPELL, &gsn_sunfire },
	{ "teleport",               DYNTYPE_SPELL, &gsn_teleport },
	{ "thorny feet",            DYNTYPE_SPELL, &gsn_thorny_feet },
	{ "totemstaff",				DYNTYPE_SPELL, &gsn_totemstaff },
	{ "tough skin",             DYNTYPE_SPELL, &gsn_tough_skin },
	{ "treeform",				DYNTYPE_SPELL, &gsn_treeform },
	{ "true sight",             DYNTYPE_SPELL, &gsn_true_sight },
	{ "citytrack",				DYNTYPE_SKILL, &gsn_citytrack},
	{ "fieldtrack",				DYNTYPE_SKILL, &gsn_fieldtrack},
	{ "unholy aura",            DYNTYPE_SPELL, &gsn_unholy_aura },
	{ "utterdark",              DYNTYPE_SPELL, &gsn_utterdark },
	{ "vampiric touch",         DYNTYPE_SPELL, &gsn_vampiric_touch },
	{ "ventriloquate",          DYNTYPE_SPELL, &gsn_ventriloquate },
	{ "wall of fire",           DYNTYPE_SPELL, &gsn_wall_of_fire },
	{ "wall of ice",            DYNTYPE_SPELL, &gsn_wall_of_ice },
	{ "weaken",                 DYNTYPE_SPELL, &gsn_weaken },
	{ "wildstrike",             DYNTYPE_SPELL, &gsn_wildstrike },
	{ "wizard eye",             DYNTYPE_SPELL, &gsn_wizard_eye },
	{ "wind shield",            DYNTYPE_SPELL, &gsn_wind_shield },
	{ "word of recall",         DYNTYPE_SPELL, &gsn_word_of_recall },
	{ "wrath",                  DYNTYPE_SPELL, &gsn_wrath },
	{ "vicegrip",				DYNTYPE_SPELL, &gsn_vicegrip  },
	{ "summon guardian",        DYNTYPE_SPELL, &gsn_summon_guardian },
	{ "element ring",           DYNTYPE_SPELL, &gsn_element_ring },
	{ "summon vyr",             DYNTYPE_SPELL, &gsn_summon_vyr },
	{ "summon justice",         DYNTYPE_SPELL, &gsn_summon_justice },
	{ "acid breath",            DYNTYPE_SPELL, &gsn_acid_breath },
	{ "fire breath",            DYNTYPE_SPELL, &gsn_fire_breath },
	{ "frost breath",           DYNTYPE_SPELL, &gsn_frost_breath },
	{ "gas breath",             DYNTYPE_SPELL, &gsn_gas_breath },
	{ "shadow breath",          DYNTYPE_SPELL, &gsn_shadow_breath },
	{ "steel breath",           DYNTYPE_SPELL, &gsn_steel_breath },
	{ "lightning breath",       DYNTYPE_SPELL, &gsn_lightning_breath },	
	{ "general purpose",        DYNTYPE_UNDEFINED, &gsn_general_purpose },
	{ "high explosive",         DYNTYPE_UNDEFINED, &gsn_high_explosive },
	{ "claw",                   DYNTYPE_SKILL, &gsn_claw },
	{ "gore",                   DYNTYPE_SKILL, &gsn_gore },
	{ "gouge",                  DYNTYPE_SKILL, &gsn_gouge },
	{ "cutoff",                 DYNTYPE_SKILL, &gsn_cutoff },
	{ "dervish",                DYNTYPE_SKILL, &gsn_dervish },
	{ "hurl",                   DYNTYPE_SKILL, &gsn_hurl },
	{ "shieldcleave",           DYNTYPE_SKILL, &gsn_shieldcleave },
	{ "hobble",                 DYNTYPE_SKILL, &gsn_hobble },
	{ "boneshatter",			DYNTYPE_SKILL, &gsn_boneshatter },
	{ "overhead",				DYNTYPE_SKILL, &gsn_overhead },
	{ "charge",                 DYNTYPE_SKILL, &gsn_charge },
	{ "sorcery",                DYNTYPE_SKILL, &gsn_sorcery },
	{ "mana focusing",          DYNTYPE_SKILL, &gsn_mana_focusing },
	{ "axe",                    DYNTYPE_SKILL, &gsn_axe },
	{ "dagger",                 DYNTYPE_SKILL, &gsn_dagger },
	{ "flail",                  DYNTYPE_SKILL, &gsn_flail },
	{ "mace",                   DYNTYPE_SKILL, &gsn_mace },
	{ "polearm",                DYNTYPE_SKILL, &gsn_polearm },
	{ "sickle",					DYNTYPE_SKILL, &gsn_sickle },
	{ "shield block",           DYNTYPE_SKILL, &gsn_shield_block },
	{ "dual wield",					DYNTYPE_SKILL, &gsn_second },
	{ "staff",                  DYNTYPE_SKILL, &gsn_staff },
	{ "sword",                  DYNTYPE_SKILL, &gsn_sword },
        { "spear",                      DYNTYPE_SKILL, &gsn_spear },
	{ "whip",                   DYNTYPE_SKILL, &gsn_whip },
	{ "apply",					DYNTYPE_SKILL, &gsn_apply },
	{ "backstab",               DYNTYPE_SKILL, &gsn_backstab },
	{ "bash",                   DYNTYPE_SKILL, &gsn_bash },
	{ "berserk",                DYNTYPE_SKILL, &gsn_berserk },
	{ "circle",					DYNTYPE_SKILL, &gsn_circle },
	{ "dirt kicking",           DYNTYPE_SKILL, &gsn_dirt_kicking },
	{ "disarm",                 DYNTYPE_SKILL, &gsn_disarm },
	{ "dodge",                  DYNTYPE_SKILL, &gsn_dodge },
	{ "entangle",               DYNTYPE_SKILL, &gsn_entangle },
	{ "enhanced damage",        DYNTYPE_SKILL, &gsn_enhanced_damage },
	{ "herblore",				DYNTYPE_SKILL, &gsn_herblore },
	{ "ultra damage",           DYNTYPE_SKILL, &gsn_ultra_damage },
	{ "envenom",                DYNTYPE_SKILL, &gsn_envenom },
	{ "hand to hand",           DYNTYPE_SKILL, &gsn_hand_to_hand },
	{ "kick",                   DYNTYPE_SKILL, &gsn_kick },
	{ "parry",                  DYNTYPE_SKILL, &gsn_parry },
	{ "pounce",                 DYNTYPE_SKILL, &gsn_pounce },
	{ "rescue",                 DYNTYPE_SKILL, &gsn_rescue },
	{ "stifle",					DYNTYPE_SKILL, &gsn_stifle },
	{ "trip",                   DYNTYPE_SKILL, &gsn_trip },
	{ "second attack",          DYNTYPE_SKILL, &gsn_second_attack },
	{ "third attack",           DYNTYPE_SKILL, &gsn_third_attack },
	{ "quad attack",            DYNTYPE_SKILL, &gsn_quad_attack },
	{ "riding",                 DYNTYPE_SKILL, &gsn_riding },
	{ "retreat",                DYNTYPE_SKILL, &gsn_retreat },
	{ "shadow",					DYNTYPE_SKILL, &gsn_shadow },
	{ "cannibalize",			DYNTYPE_SKILL, &gsn_cannibalize },
	{ "animal training",        DYNTYPE_SKILL, &gsn_animal_training },
	{ "domesticate",            DYNTYPE_SKILL, &gsn_domesticate },
	{ "brew",                   DYNTYPE_SKILL, &gsn_brew },
	{ "diagnose",               DYNTYPE_SKILL, &gsn_diagnose },
	{ "scribe",                 DYNTYPE_SKILL, &gsn_scribe },
	{ "slice",                  DYNTYPE_SKILL, &gsn_slice },
	{ "forage",                 DYNTYPE_SKILL, &gsn_forage },
	{ "build",                  DYNTYPE_SKILL, &gsn_build },
	{ "cook",                   DYNTYPE_SKILL, &gsn_cook },
	{ "awareness",              DYNTYPE_SKILL, &gsn_awareness },
	{ "channel",                DYNTYPE_SKILL, &gsn_channel },
	{ "fast healing",           DYNTYPE_SKILL, &gsn_fast_healing },
	{ "fork",					DYNTYPE_SKILL, &gsn_fork },
	{ "haggle",                 DYNTYPE_SKILL, &gsn_haggle },
	{ "hide",                   DYNTYPE_SKILL, &gsn_hide },
	{ "lay on hands",           DYNTYPE_SKILL, &gsn_lay_on_hands },
	{ "lore",                   DYNTYPE_SKILL, &gsn_lore },
	{ "meditation",             DYNTYPE_SKILL, &gsn_meditation },
	{ "peek",                   DYNTYPE_SKILL, &gsn_peek },
	{ "pick lock",              DYNTYPE_SKILL, &gsn_pick_lock },
	{ "place",					DYNTYPE_SKILL, &gsn_place },
	{ "scan",                   DYNTYPE_SKILL, &gsn_scan },
	{ "sharpen",                DYNTYPE_SKILL, &gsn_sharpen },
	{ "sneak",                  DYNTYPE_SKILL, &gsn_sneak },
	{ "steal",                  DYNTYPE_SKILL, &gsn_steal },
	{ "scrolls",                DYNTYPE_SKILL, &gsn_scrolls },
	{ "staves",                 DYNTYPE_SKILL, &gsn_staves },
	{ "wands",                  DYNTYPE_SKILL, &gsn_wands },
	{ "vault",					DYNTYPE_SKILL, &gsn_vault },
	{ "vanish",                 DYNTYPE_SKILL, &gsn_vanish },
	{ "recall",                 DYNTYPE_SKILL, &gsn_recall },

	// Languages
	{ "native",                 DYNTYPE_SKILL, &gsn_native },
	{ "human",                  DYNTYPE_SKILL, &gsn_human },
	{ "elven",                  DYNTYPE_SKILL, &gsn_elven },
	{ "dwarven",                DYNTYPE_SKILL, &gsn_dwarven },
	{ "draconian",              DYNTYPE_SKILL, &gsn_draconian },
	{ "gnomish",                DYNTYPE_SKILL, &gsn_gnomish },
	{ "halfling",               DYNTYPE_SKILL, &gsn_halfling },
	{ "orcish",                 DYNTYPE_SKILL, &gsn_orcish },
	{ "drow",                   DYNTYPE_SKILL, &gsn_drow },
	{ "avian",                  DYNTYPE_SKILL, &gsn_avian },
	{ "gnoll",                  DYNTYPE_SKILL, &gsn_gnoll },
	{ "lizardman",              DYNTYPE_SKILL, &gsn_lizardman },
	{ "alaghi",                 DYNTYPE_SKILL, &gsn_alaghi },
	{ "goblin",                 DYNTYPE_SKILL, &gsn_goblin },
	{ "haxor",                  DYNTYPE_SKILL, &gsn_haxor },
	{ "kobold",                 DYNTYPE_SKILL, &gsn_kobold },
	{ "arcaic",                 DYNTYPE_SKILL, &gsn_arcaic },
	{ "reverse",                DYNTYPE_SKILL, &gsn_reverse },
	{ "search",					DYNTYPE_SKILL, &gsn_search },
	{ "trollish",				DYNTYPE_SKILL, &gsn_trollish },
	{ "faerie",					DYNTYPE_SKILL, &gsn_faerie },
	{ "mremish",                DYNTYPE_SKILL, &gsn_mremish },
	{ NULL, DYNTYPE_UNDEFINED, NULL}
};

dynspell_type spellpairs_table[]={
	{ 0,	"spell_null", spell_null, TAR_IGNORE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_acid_blast", spell_acid_blast, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_alarm", spell_alarm, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_animal_essence", spell_animal_essence, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_armor", spell_armor, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE,	"spell_augment_hearing", spell_augment_hearing, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE,	"spell_aura_of_temperance", spell_aura_of_temperance, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE,	"spell_barkskin", spell_barkskin, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE,	"spell_benedict", spell_benedict, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_bless", spell_bless, TAR_OBJ_CHAR_DEF},
	{ SPFUNC_NODAMTYPE, "spell_blessed_garments", spell_blessed_garments, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_DAMTYPE,	"spell_blindness", spell_blindness, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE,	"spell_sb_blindness", spell_sb_blindness, TAR_CHAR_OFFENSIVE}, //Meerclar
	{ SPFUNC_NODAMTYPE,	"spell_blink", spell_blink, TAR_DIRECTION},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_burning_hands", spell_burning_hands, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_call_lightning", spell_call_lightning, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_calm", spell_calm, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_sb_calm", spell_sb_calm, TAR_IGNORE}, //Meerclar
	{ SPFUNC_NODAMTYPE, "spell_cancellation", spell_cancellation, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_canticle_of_warding", spell_canticle_of_warding, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_cantrip", spell_cantrip, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_cause_fear", spell_cause_fear, TAR_MOB_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_cause_headache", spell_cause_headache, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_cause_critical", spell_cause_critical, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_cause_light", spell_cause_light, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_cause_serious", spell_cause_serious, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_chain_lightning", spell_chain_lightning, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_change_sex", spell_change_sex, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_charm_person", spell_charm_person, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_chaos_lace", spell_chaos_lace, TAR_OBJ_INV},
	{ SPFUNC_DAMTYPE, "spell_chaotic_poison", spell_chaotic_poison, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_chill_shield", spell_chill_shield, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_chill_touch", spell_chill_touch, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_colour_spray", spell_colour_spray, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_commune_with_dead", spell_commune_with_dead, TAR_OBJ_INV},
	{ SPFUNC_DAMTYPE, "spell_cone_cold", spell_cone_cold, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_continual_light", spell_continual_light, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_control_weather", spell_control_weather, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_create_bouquet", spell_create_bouquet, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_create_buffet", spell_create_buffet, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_create_food", spell_create_food, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_create_rose", spell_create_rose, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_create_spring", spell_create_spring, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_create_water", spell_create_water, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_cure_blindness", spell_cure_blindness, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_cure_chaotic_poison", spell_cure_chaotic_poison, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_cure_critical", spell_cure_critical, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_sb_cure_critical", spell_sb_cure_critical, TAR_CHAR_DEFENSIVE}, //Meerclar
	{ SPFUNC_NODAMTYPE, "spell_cure_deafness", spell_cure_deafness, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_cure_disease", spell_cure_disease, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_cure_headache", spell_cure_headache, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_cure_light", spell_cure_light, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_sb_cure_light", spell_sb_cure_light, TAR_CHAR_DEFENSIVE}, //Meerclar
	{ SPFUNC_NODAMTYPE, "spell_cure_poison", spell_cure_poison, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_cure_serious", spell_cure_serious, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_sb_cure_serious", spell_sb_cure_serious, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_curse", spell_curse, TAR_OBJ_MOB_OFF},
	{ SPFUNC_DAMTYPE, "spell_cutting_wind", spell_cutting_wind, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_cyclone", spell_cyclone, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_DAMTYPE,	"spell_deafness", spell_deafness, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_decay", spell_decay, TAR_OBJ_CHAR_OFF},
	{ SPFUNC_NODAMTYPE, "spell_detect_evil", spell_detect_evil, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_detect_good", spell_detect_good, TAR_CHAR_SELF},
	{ SPFUNC_DAMTYPE, "spell_dehydration", spell_dehydration, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_detect_hidden", spell_detect_hidden, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_detect_invis", spell_detect_invis, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_detect_magic", spell_detect_magic, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_detect_poison", spell_detect_poison, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_detect_scry", spell_detect_scry, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_detect_treeform", spell_detect_treeform, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_disorientation", spell_disorientation, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_dispel_evil", spell_dispel_evil, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_dispel_good", spell_dispel_good, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_dispel_magic", spell_dispel_magic, TAR_MOB_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_divine_light",	spell_divine_light,	TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_downdraft", spell_downdraft, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_dragon_strength", spell_dragon_strength, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_druidstaff", spell_druidstaff, TAR_IGNORE },
	{ SPFUNC_DAMTYPE, "spell_drunkeness", spell_drunkeness, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_drain_blade", spell_drain_blade, TAR_OBJ_INV},
	{ SPFUNC_DAMTYPE, "spell_earthquake", spell_earthquake, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_earthwalk", spell_earthwalk, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_empower_blade", spell_empower_blade, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_enchant_armor", spell_enchant_armor, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_enchant_item",	spell_enchant_item, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_enchant_weapon", spell_enchant_weapon, TAR_OBJ_INV},	
	{ SPFUNC_NODAMTYPE, "spell_energy_drain", spell_energy_drain, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_extension", spell_extension, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_faerie_fire", spell_faerie_fire, TAR_MOB_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_faerie_fog", spell_faerie_fog, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_farsight", spell_farsight, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_fear_magic", spell_fear_magic, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_fiery_armour", spell_fiery_armour, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_fireball", spell_fireball, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_fireproof", spell_fireproof, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_fire_shield", spell_fire_shield, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_frostball", spell_frostball, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_flame_blade", spell_flame_blade, TAR_OBJ_INV},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_flamestrike", spell_flamestrike, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_fling", spell_fling, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_fly", spell_fly, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_floating_disc", spell_floating_disc, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_frenzy", spell_frenzy, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_frost_blade", spell_frost_blade, TAR_OBJ_INV},
	{ SPFUNC_DAMTYPE, "spell_gate", spell_gate, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_sb_gate", spell_sb_gate, TAR_IGNORE}, // -Balo-
	{ SPFUNC_NODAMTYPE, "spell_giant_strength", spell_giant_strength, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_harm", spell_harm, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_haste", spell_haste, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_heal", spell_heal, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_heat_metal", spell_heat_metal, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_high_area_attack", spell_high_area_attack, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_higher_learning", spell_higher_learning, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_holy_aura", spell_holy_aura, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_holy_beam", spell_holy_beam, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_holy_word", spell_holy_word, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_sb_holy_word", spell_sb_holy_word, TAR_IGNORE}, //Meerclar
	{ SPFUNC_DAMTYPE, "spell_ice_storm", spell_ice_storm, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_icy_armour", spell_icy_armour, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_identify", spell_identify, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_illusions_grandeur", spell_illusions_grandeur, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_sb_illusions_grandeur", spell_sb_illusions_grandeur, TAR_CHAR_SELF},
	{ SPFUNC_DAMTYPE, "spell_immolation", spell_immolation, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_improved_phantasm", spell_improved_phantasm, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_induce_sleep", spell_induce_sleep, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_infravision", spell_infravision, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_invisibility", spell_invisibility, TAR_OBJ_CHAR_DEF},
	{ SPFUNC_NODAMTYPE, "spell_iron_skin", spell_iron_skin, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_know_alignment", spell_know_alignment, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_lightning_bolt", spell_lightning_bolt, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_locate_object", spell_locate_object, TAR_IGNORE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_low_area_attack", spell_low_area_attack, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_magic_resistance", spell_magic_resistance, TAR_CHAR_SELF},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_magic_missile", spell_magic_missile, TAR_CHAR_OFFENSIVE},
  { SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_sb_magic_missile", spell_sb_magic_missile, TAR_CHAR_OFFENSIVE}, //Meerclar
	{ SPFUNC_NODAMTYPE, "spell_magical_vestment", spell_magical_vestment, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_maledict", spell_maledict, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_mass_healing", spell_mass_healing, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_mass_invis", spell_mass_invis, TAR_IGNORE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_mid_area_attack", spell_mid_area_attack, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_mirage", spell_mirage, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_mithril_glaze", spell_mithril_glaze, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_mindspeak", spell_mindspeak, TAR_IGNORE},
	{ SPFUNC_DAMTYPE,	"spell_mute", spell_mute, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_naturespeak", spell_naturespeak, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_nexus", spell_nexus, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_night_of_the_leonids", spell_night_of_the_leonids, TAR_IGNORE },
	{ SPFUNC_NODAMTYPE, "spell_oak_shield", spell_oak_shield, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_ogre_strength", spell_ogre_strength, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_otterlungs", spell_otterlungs, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_pass_door", spell_pass_door, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_pass_without_trace", spell_pass_without_trace, TAR_CHAR_SELF},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_phantasmal_force", spell_phantasmal_force, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_permanance", spell_permanance, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_pine_needles", spell_pine_needles, TAR_CHAR_SELF},
	{ SPFUNC_DAMTYPE, "spell_plague", spell_plague, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_poison", spell_poison, TAR_OBJ_MOB_OFF},
	{ SPFUNC_NODAMTYPE, "spell_poison_immunity", spell_poison_immunity, TAR_CHAR_SELF},
	{ SPFUNC_DAMTYPE, "spell_poison_rain", spell_poison_rain, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_sb_poison_rain", spell_sb_poison_rain, TAR_IGNORE}, //Meerclar
	{ SPFUNC_DAMTYPE, "spell_portal", spell_portal, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_sb_portal", spell_sb_portal, TAR_IGNORE}, // -Balo-
	{ SPFUNC_NODAMTYPE, "spell_possession", spell_possession, TAR_CHAR_SELF},	
	{ SPFUNC_NODAMTYPE, "spell_prayer", spell_prayer, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_prismatic_spray", spell_prismatic_spray, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_protection_acid", spell_protection_acid, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_protection_cold", spell_protection_cold, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_protection_evil", spell_protection_evil, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_sb_protection_evil", spell_sb_protection_evil, TAR_CHAR_SELF},//Meerclar
	{ SPFUNC_NODAMTYPE, "spell_protection_fire", spell_protection_fire, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_protection_good", spell_protection_good, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_sb_protection_good", spell_sb_protection_good, TAR_CHAR_SELF},//Meerclar
	{ SPFUNC_NODAMTYPE, "spell_protection_lightning", spell_protection_lightning, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_rage", spell_rage, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_recharge", spell_recharge, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_refresh", spell_refresh, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_regeneration", spell_regeneration, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_rejuvinate", spell_rejuvinate, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_remove_alignment", spell_remove_alignment, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_remove_curse", spell_remove_curse, TAR_OBJ_CHAR_DEF},
	{ SPFUNC_NODAMTYPE, "spell_resist_poison", spell_resist_poison, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_resist_weapons", spell_resist_weapons, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_restore_mana", spell_restore_mana, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_rocky_skin", spell_rocky_skin, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_rune_edge", spell_rune_edge, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_runic_blade", spell_runic_blade, TAR_OBJ_INV},
	{ SPFUNC_NODAMTYPE, "spell_sanctuary", spell_sanctuary, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_shadowflight", spell_shadowflight, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_shaping_the_chaos", spell_shaping_the_chaos, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_shelter", spell_shelter, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_shield", spell_shield, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_shrink", spell_shrink, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_shocking_grasp", spell_shocking_grasp, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_sleep", spell_sleep, TAR_MOB_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_slow", spell_slow, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_smite", spell_smite, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_spirit_hammer", spell_spirit_hammer, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_spirit_walk", spell_spirit_walk, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_stone_skin", spell_stone_skin, TAR_CHAR_SELF},
	{ SPFUNC_DAMTYPE, "spell_starvation", spell_starvation, TAR_MOB_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_sober", spell_sober, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_strength_of_the_land", spell_strength_of_the_land, TAR_CHAR_SELF},
	{ SPFUNC_DAMTYPE, "spell_sb_strength_of_the_land", spell_sb_strength_of_the_land, TAR_CHAR_SELF},//Meerclar
	{ SPFUNC_DAMTYPE, "spell_summon", spell_summon, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_sunfire", spell_sunfire, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_teleport", spell_teleport, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_totemstaff", spell_totemstaff, TAR_IGNORE },
	{ SPFUNC_DAMTYPE, "spell_thorny_feet", spell_thorny_feet, TAR_MOB_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_tough_skin", spell_tough_skin, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_treeform", spell_treeform, TAR_CHAR_SELF },
	{ SPFUNC_NODAMTYPE, "spell_true_sight", spell_true_sight, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_unholy_aura", spell_unholy_aura, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_utterdark", spell_utterdark, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_vampiric_touch", spell_vampiric_touch, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_ventriloquate", spell_ventriloquate, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_wall_of_fire", spell_wall_of_fire, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_NODAMTYPE, "spell_wall_of_ice", spell_wall_of_ice, TAR_CHAR_DEFENSIVE },
	{ SPFUNC_DAMTYPE, "spell_weaken", spell_weaken, TAR_MOB_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_wildstrike", spell_wildstrike, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_wizard_eye", spell_wizard_eye, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_wind_shield", spell_wind_shield, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_word_of_recall", spell_word_of_recall, TAR_CHAR_SELF},
	{ SPFUNC_NODAMTYPE, "spell_sb_word_of_recall", spell_sb_word_of_recall, TAR_CHAR_SELF},//Meerclar
	{ SPFUNC_DAMTYPE, "spell_wrath", spell_wrath, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_vicegrip", spell_vicegrip, TAR_CHAR_SELF },//Meerclar
	{ SPFUNC_NODAMTYPE, "spell_summon_guardian", spell_summon_guardian, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_element_ring", spell_element_ring, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_summon_vyr", spell_summon_vyr, TAR_IGNORE},
	{ SPFUNC_NODAMTYPE, "spell_summon_justice", spell_summon_justice, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_acid_breath", spell_acid_breath, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_fire_breath", spell_fire_breath, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_frost_breath", spell_frost_breath, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_DAMTYPE, "spell_gas_breath", spell_gas_breath, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_shadow_breath", spell_shadow_breath, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_steel_breath", spell_steel_breath, TAR_IGNORE},
	{ SPFUNC_DAMTYPE, "spell_lightning_breath", spell_lightning_breath, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NODAMTYPE, "spell_logic", spell_logic, TAR_CHAR_SELF },
	{ SPFUNC_NODAMTYPE, "spell_mnemonics", spell_mnemonics, TAR_CHAR_SELF },
	{ SPFUNC_NODAMTYPE, "spell_lucidity", spell_lucidity, TAR_CHAR_SELF },
	{ SPFUNC_NODAMTYPE, "spell_clarity", spell_clarity, TAR_CHAR_SELF },
	{ SPFUNC_NODAMTYPE, "spell_persuasion", spell_persuasion, TAR_CHAR_SELF },
	{ SPFUNC_NODAMTYPE, "spell_night_eyes", spell_night_eyes, TAR_CHAR_DEFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_general_purpose", spell_general_purpose, TAR_CHAR_OFFENSIVE},
	{ SPFUNC_NOTEXT|SPFUNC_DAMTYPE, "spell_high_explosive", spell_high_explosive, TAR_CHAR_OFFENSIVE},
	{ 0, "", NULL, TAR_IGNORE}
};
